name: CI

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      #https://github.com/docker/build-push-action/issues/281#issuecomment-766168048
      # By default, this action uses the Git context so you don't need to use the actions/checkout action to checkout the repository
      # because this will be done directly by buildkit. The git reference will be based on the event that triggered your workflow
      # and will result in the following context: https://github.com/<owner>/<repo>.git#<ref>.
      -
        name: Checkout
        uses: actions/checkout@v4.2.1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push [8.0]
        uses: docker/build-push-action@v6
        with:
          context: ./8.0
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bitnami-php-fpm:8.0
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push [8.1]
        uses: docker/build-push-action@v6
        with:
          context: ./8.1
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bitnami-php-fpm:8.1
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push [8.2]
        uses: docker/build-push-action@v6
        with:
          context: ./8.2
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bitnami-php-fpm:8.2
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push [8.3, latest]
        uses: docker/build-push-action@v6
        with:
          context: ./8.3
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bitnami-php-fpm:8.3,${{ secrets.DOCKERHUB_USERNAME }}/bitnami-php-fpm:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max  
      # Docker Hub Personal Access Tokens cannot be used as they are not supported by the API.
      # Unfortunately, this means that enabling 2FA on Docker Hub will prevent the action from working.
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/bitnami-php-fpm
          short-description: ${{ github.event.repository.description }}
